# Generated by Django 5.2.12 on 2026-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('site', models.URLField(blank='true', null='true')),
            ],
        ),
    ]
