# Generated by Django 5.2.12 on 2026-04-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_editota'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editota',
            new_name='Editora',
        ),
    ]
